apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: presync-job
        image: alpine:latest
        env:
        - name: condition
          value: "true"
        command:
        - /bin/sh
        - -c
        - >
          print_something () {
            apk update && apk add --no-cache curl bash
            echo "Hello I am a function"
            curl -i -H "Accept: application/json" http://34.100.140.136:8080/job/slack_notif/build?token=token123 --user gangadhar:11e616607d1ca4ca1d264d2d645780ad22 | grep Location | awk '{print $2}'
            echo "after curl cmd"
            } && print_something
      restartPolicy: OnFailure
  backoffLimit: 4
