apiVersion: batch/v1
kind: Job
metadata:
  generateName: schema-migrate-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: presync-job
        image: alpine:latest
        env:
        - name: condition
          value: "true"
        command:
        - /bin/sh
        - -c
        - >
          print_something () {
            apk update && apk add --no-cache curl bash
            echo "Hello I am a function"
            awk --version
            } && print_something
      restartPolicy: OnFailure
  backoffLimit: 4
